services:
  database:
    image: 'zulip/zulip-postgresql:14'
    restart: unless-stopped
    environment:
      POSTGRES_DB: zulip
      POSTGRES_USER: zulip
      POSTGRES_PASSWORD: ${SECRETS_postgres_password}
    volumes:
      - 'postgresql-14:/var/lib/postgresql/data:rw'
  memcached:
    image: 'memcached:alpine'
    restart: unless-stopped
    command:
      - sh
      - '-euc'
      - |
        echo 'mech_list: plain' > "$$SASL_CONF_PATH"
        echo "zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
        echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
        exec memcached -S
    environment:
      SASL_CONF_PATH: /home/memcache/memcached.conf
      MEMCACHED_SASL_PWDB: /home/memcache/memcached-sasl-db
      MEMCACHED_PASSWORD: ${SECRETS_memcached_password}
  rabbitmq:
    image: 'rabbitmq:4.0.7'
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: zulip
      RABBITMQ_DEFAULT_PASS: ${SECRETS_rabbitmq_password}
    volumes:
      - 'rabbitmq:/var/lib/rabbitmq:rw'
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    command:
      - sh
      - '-euc'
      - |
        echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: ${SECRETS_redis_password}
    volumes:
      - 'redis:/data:rw'
  zulip:
    image: 'zulip/docker-zulip:10.2-0'
    restart: unless-stopped
    build:
      context: .
      args:
        ZULIP_GIT_URL: 'https://github.com/zulip/zulip.git'
        ZULIP_GIT_REF: '10.2'
    # ports:
    #   - '80:80'
    #   - '443:443'
    environment:
      DB_HOST: database
      DB_HOST_PORT: '5432'
      DB_USER: zulip
      SSL_CERTIFICATE_GENERATION: self-signed
      SETTING_MEMCACHED_LOCATION: 'memcached:11211'
      SETTING_RABBITMQ_HOST: rabbitmq
      SETTING_REDIS_HOST: redis
      SECRETS_email_password: ${SECRETS_email_password}
      SECRETS_rabbitmq_password: ${SECRETS_rabbitmq_password}
      SECRETS_postgres_password: ${SECRETS_postgres_password}
      SECRETS_memcached_password: ${SECRETS_memcached_password}
      SECRETS_redis_password: ${SECRETS_redis_password}
      SECRETS_secret_key: ${SECRETS_secret_key}
      SETTING_EXTERNAL_HOST: zulip.dev-book.me
      SETTING_ZULIP_ADMINISTRATOR: ${ADMIN_email}
      SETTING_EMAIL_HOST: smtp.gmail.com
      SETTING_EMAIL_HOST_USER: zulip.devbook.me@gmail.com
      SETTING_EMAIL_PORT: '587'
      SETTING_EMAIL_USE_SSL: 'False'
      SETTING_EMAIL_USE_TLS: 'True'
      ZULIP_AUTH_BACKENDS: EmailAuthBackend
      DISABLE_HTTPS: "True"
      LOADBALANCER_IPS: "172.16.0.0/12,192.168.0.0/16" 
    volumes:
      - 'zulip:/data:rw'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1048576
volumes:
  zulip:
  postgresql-14:
  rabbitmq:
  redis:
